on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Logbook on Elixir ${{matrix.elixir}} (OTP ${{matrix.otp}})
    strategy:
      matrix:
        otp: ["24", "26", "27"]
        elixir: ["1.14.5", "1.17.3", "1.18.3"]
        exclude:
          - elixir: 1.14.5
            otp: 27
          - elixir: 1.17.3
            otp: 24
          - elixir: 1.18.3
            otp: 24
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
